version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: 
        - command:
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - store_test_results:
          path: test-results

