version: 2.1

jobs:
  build:
    working_directory: ~/circleci-demo-python-flask
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv book_env
            pip install -r requirements.txt
      - store_test_results:
          path: test-results
