version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: mkdir test-results
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          # deps1-master-3984FA
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Launch Flask
          command: |
            source venv/bin/activate
            python bookapp/app.py
          background: true 
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest > test.log
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_test_results:
          path: test-results
